# Generated by Django 5.2.11 on 2026-02-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_evento_tipo_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficina',
            options={'ordering': ['-semestre__nome', 'nome'], 'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
        migrations.AddField(
            model_name='oficina',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='oficinas', to='schedule.semestre', verbose_name='Semestre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local'),
        ),
    ]
