from django.urls import path

from schedule import views

urlpatterns = [
    # ── Públicas ───────────────────────────────────────────────
    path('', views.AgendaView.as_view(), name='home'),
    path(
        'api/eventos/',
        views.EventosApiView.as_view(),
        name='api_eventos',
    ),
    path(
        'evento/<int:pk>/detalhes/',
        views.EventoDetalhesView.as_view(),
        name='evento_detalhes',
    ),
    path(
        'evento/<int:pk>/presenca/',
        views.PresencaView.as_view(),
        name='evento_presenca',
    ),
    # ── Dashboard ──────────────────────────────────────────────
    path(
        'gestao/',
        views.DashboardView.as_view(),
        name='dashboard',
    ),
    # ── Semestre CRUD ──────────────────────────────────────────
    path(
        'gestao/semestres/',
        views.SemestreListView.as_view(),
        name='semestre_list',
    ),
    path(
        'gestao/semestres/novo/',
        views.SemestreCreateView.as_view(),
        name='semestre_create',
    ),
    path(
        'gestao/semestres/<int:pk>/editar/',
        views.SemestreUpdateView.as_view(),
        name='semestre_update',
    ),
    path(
        'gestao/semestres/<int:pk>/excluir/',
        views.SemestreDeleteView.as_view(),
        name='semestre_delete',
    ),
    # ── Turma CRUD ─────────────────────────────────────────────
    path(
        'gestao/turmas/',
        views.TurmaListView.as_view(),
        name='turma_list',
    ),
    path(
        'gestao/turmas/nova/',
        views.TurmaCreateView.as_view(),
        name='turma_create',
    ),
    path(
        'gestao/turmas/<int:pk>/editar/',
        views.TurmaUpdateView.as_view(),
        name='turma_update',
    ),
    path(
        'gestao/turmas/<int:pk>/excluir/',
        views.TurmaDeleteView.as_view(),
        name='turma_delete',
    ),
    path(
        'gestao/turmas/<int:pk>/copiar/',
        views.TurmaCopiarView.as_view(),
        name='turma_copiar',
    ),
    # ── Oficina CRUD ───────────────────────────────────────────
    path(
        'gestao/oficinas/',
        views.OficinaListView.as_view(),
        name='oficina_list',
    ),
    path(
        'gestao/oficinas/nova/',
        views.OficinaCreateView.as_view(),
        name='oficina_create',
    ),
    path(
        'gestao/oficinas/lote/',
        views.OficinaBulkCreateView.as_view(),
        name='oficina_bulk_create',
    ),
    path(
        'gestao/oficinas/<int:pk>/editar/',
        views.OficinaUpdateView.as_view(),
        name='oficina_update',
    ),
    path(
        'gestao/oficinas/<int:pk>/excluir/',
        views.OficinaDeleteView.as_view(),
        name='oficina_delete',
    ),
    # ── Aluno CRUD ─────────────────────────────────────────────
    path(
        'gestao/alunos/',
        views.AlunoListView.as_view(),
        name='aluno_list',
    ),
    path(
        'gestao/alunos/novo/',
        views.AlunoCreateView.as_view(),
        name='aluno_create',
    ),
    path(
        'gestao/alunos/lote/',
        views.AlunoBulkCreateView.as_view(),
        name='aluno_bulk_create',
    ),
    path(
        'gestao/alunos/<int:pk>/',
        views.AlunoDetailView.as_view(),
        name='aluno_detail',
    ),
    path(
        'gestao/alunos/<int:pk>/editar/',
        views.AlunoUpdateView.as_view(),
        name='aluno_update',
    ),
    path(
        'gestao/alunos/<int:pk>/excluir/',
        views.AlunoDeleteView.as_view(),
        name='aluno_delete',
    ),
    # ── Evento CRUD ────────────────────────────────────────────
    path(
        'gestao/eventos/',
        views.EventoListView.as_view(),
        name='evento_list',
    ),
    path(
        'gestao/eventos/novo/',
        views.EventoCreateView.as_view(),
        name='evento_create',
    ),
    path(
        'gestao/eventos/<int:pk>/',
        views.EventoDetailView.as_view(),
        name='evento_detail_gestao',
    ),
    path(
        'gestao/eventos/<int:pk>/editar/',
        views.EventoUpdateView.as_view(),
        name='evento_update',
    ),
    path(
        'gestao/eventos/<int:pk>/excluir/',
        views.EventoDeleteView.as_view(),
        name='evento_delete',
    ),
    path(
        'gestao/eventos/<int:pk>/alocar/',
        views.EventoAlocarView.as_view(),
        name='evento_alocar',
    ),
    path(
        'gestao/alocacao/<int:pk>/remover/',
        views.AlocacaoRemoverView.as_view(),
        name='alocacao_remover',
    ),
    path(
        'gestao/eventos/<int:pk>/cancelar/',
        views.EventoCancelarView.as_view(),
        name='evento_cancelar',
    ),
    # ── Relatórios ─────────────────────────────────────────────
    path(
        'gestao/relatorios/',
        views.RelatorioGeralView.as_view(),
        name='relatorio_geral',
    ),
    path(
        'gestao/relatorios/turma/',
        views.RelatorioPresencaTurmaView.as_view(),
        name='relatorio_turma',
    ),
    path(
        'gestao/relatorios/evento/',
        views.RelatorioPresencaEventoView.as_view(),
        name='relatorio_evento',
    ),
    path(
        'gestao/relatorios/aluno/<int:pk>/',
        views.RelatorioPresencaAlunoView.as_view(),
        name='relatorio_aluno',
    ),
]
